### ISSUE TITLE
请问这个证书验证问题您碰到过吗，一启动providerdemo就有这个

### ISSUE THREAD

**Issue by fnbory** [chenshun00/fuck-rpc#1]
java.security.cert.CertificateException: No subject alternative DNS name matching www.huzhurong.top found.

**Comment by chenshun00** [comment]
应该是 Spring 的 `xsd` 解析的问题，我本地看看

**Comment by chenshun00** [comment]
@fnbory 你是什么环境，我本地是正常的 :(  

![image](https://user-images.githubusercontent.com/26037282/64910613-d1dd3e00-d74a-11e9-9e8e-f8e3e5f56763.png)

**Comment by fnbory** [comment]
thanks，搞好了，确实是解析的问题，我忘了把handlers和schemas放到META-INF里边了
